### ISSUE TITLE
Draggable Dom not working post react-konva-utils 0.1.5

### ISSUE THREAD

**Issue by noamackerman** [konvajs/react-konva-utils#10]
Hi,
I'm using this demo to make a draggable html element:
https://codesandbox.io/s/react-konva-utils-draggable-dom-jolg8?file=/package.json:236-253
When using the latest react-konva-utils version (0.2.0) it does not work. I checked and it seems that the regression happens with any version after (not including) 0.1.5

**Comment by lavrton** [comment]
It doesn't work because of this line: https://github.com/konvajs/react-konva-utils/commit/c294c60f35dafef7374f6c0b9436082a4d8245bb#diff-5e0a9e5ceabc1c264bd177f1f34c5c0753caba030f6da1938e3a3659a19e56e3L73

Even in konva@8 was changed. 

Why `konva@8` is an issue for you, if `react-konva-utils` is already just ES module. If it works for you, Konva should work too.
