### ISSUE TITLE
HTML Component Attempts to Unmount synchronously when removed from the DOM

### ISSUE THREAD

**Issue by markcnunes** [konvajs/react-konva-utils#26]
I see there is an issue opened already mentioning the unmount synchronously warning:
https://github.com/konvajs/react-konva-utils/issues/25

But I am opening a new issue because what I want to raise only appears when `Html` is removed from the DOM. See the example below:

https://user-images.githubusercontent.com/18724600/220667212-595baf52-170a-4f63-979c-2e2e18a8597e.mp4

I noticed this issue is related to how Konva is imported in Next.js ([as mentioned in this other issue](https://github.com/konvajs/react-konva/issues/588#issuecomment-892895335)) because I tested it in a [React environment without Next.js](https://codesandbox.io/s/react-konva-utils-delete-dom-uv2crb?file=/src/index.js:272-343) and the error didn't happen when the Html was removed from the DOM.

[Here is a reproducible repository with Html and Next.js](https://codesandbox.io/p/sandbox/solitary-frog-cleyvp?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A3%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A3%7D%5D&file=%2Flibrary%2FCanvas%2FCanvas.tsx)

**Comment by davesargrad** [comment]
@markcnunes Thanks for posting this... see issue 25.. :)

**Comment by markcnunes** [comment]
@davesargrad no worries, I saw that issue before creating this one and I mentioned it in the description. However, my case only happens when I remove the Html from the canvas, otherwise, it works fine for Next.js but it is good to know your issue happens with create_react_app. I will let the maintainers decide if this is exactly the same issue you mentioned and close this one if it makes sense.

**Comment by davesargrad** [comment]
@markcnunes Ty for that thought. As I think about when it is happening to me, I think it may also be that Html is being removed from the DOM. I have a single page application (SPA).. There are many views. The error I see happens when one of the views that has a Konva canvas is redrawn with other information. At that point, I think the Html component is unmounted (from the DOM), and then remounted in the new view. So I really think that your finding is a great finding. I think under the covers they may be the same fundamental issue with the code.

**Comment by lavrton** [comment]
Thanks for the reproducible repo. It should be fixed with `react-konva-utils@1.0.3`.
